### PR TITLE
Remove tabs in JSON data and backslash-escape double quotes

### PR DESCRIPTION
**Pull request by msabramo**
This hubot script wasn't working for me for a while, because we have JIRA tickets with junk like tabs in them that confuse this script.

This was how I got it to work for us.

### CODE REVIEW

**Comment by emiloberg** [comment]
Awesome! Thanks for this!

I reworked your PR little bit. The `safe` handlebars helper (renamed from your `cleanString`) now escapes both `\` and `"` which are invalid JSON.

Could you pull the branch (msabramo-remove_tabs_2)[https://github.com/emiloberg/hubot-jira-servant/tree/msabramo-remove_tabs_2] and see if everything works as it should for you?

N.B. I guess you added a lot of `{{cleanString something}}` in your handlebars template? It's now named `{{safe something}}`.

**Comment by msabramo** [comment]
I just did a quick test using hubot in shell mode ad it worked!

Thank you!

**Comment by emiloberg** [comment]
Once again: Thank you!

v1.2.0 with these changes are now on NPM.

**Comment by msabramo** [comment]
And thank you as well for open sourcing this!

**Pull request merged**
